### ISSUE TITLE
Causing fatal crashes on windows!

### ISSUE THREAD

**Issue by ShenKang4181** [onelei/OneBrowser#1]
Windows Irregular black screen after opening a file！
![image](https://user-images.githubusercontent.com/50401776/98755385-613fb900-2403-11eb-98aa-2efaef03b03a.png)

**Comment by onelei** [comment]
The content of this project has not been submitted yet.

**Comment by onelei** [comment]
> Windows Irregular black screen after opening a file！
> ![image](https://user-images.githubusercontent.com/50401776/98755385-613fb900-2403-11eb-98aa-2efaef03b03a.png)

The content of this project has not been submitted yet.
